# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1556N3r0_slf10sFdTe7eYeWzgycjvQuj
"""

n =7;
print (n*n)